#!/usr/bin/env python3
"""Fetch Trevelyan's Type Tester chapters into public/book.js.

The book source lives at github.com/nicoverbruggen/type-tester-epub. This
script pulls each XHTML section over raw.githubusercontent.com, strips the
XHTML scaffolding down to the body contents, and writes a single `BOOK`
global for index.js to render.

Usage:
    python3 fetch_book.py [--branch BRANCH]
"""
from __future__ import annotations
import argparse
import json
import os
import re
import sys
import urllib.request

REPO = "nicoverbruggen/type-tester-epub"
SECTIONS = [
    "prologue",
    "chapter1", "chapter2", "chapter3", "chapter4",
    "chapter5", "chapter6", "chapter7", "chapter8",
    "epilogue",
    "appendix",
]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "public", "book.js")


def fetch(branch: str, name: str) -> str:
    url = f"https://raw.githubusercontent.com/{REPO}/{branch}/src/OEBPS/{name}.xhtml"
    with urllib.request.urlopen(url, timeout=20) as r:
        return r.read().decode("utf-8")


def extract(xhtml: str) -> tuple[str, str, str]:
    """Return (title, body-class, body-html)."""
    title_m = re.search(r"<title[^>]*>(.*?)</title>", xhtml, re.S)
    body_m = re.search(r"<body([^>]*)>(.*)</body>", xhtml, re.S)
    title = title_m.group(1).strip() if title_m else ""
    attrs = body_m.group(1) if body_m else ""
    body = body_m.group(2).strip() if body_m else ""
    cls_m = re.search(r'class="([^"]*)"', attrs)
    cls = cls_m.group(1) if cls_m else ""
    return title, cls, body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--branch", default="main")
    args = parser.parse_args()

    chapters = []
    for name in SECTIONS:
        print(f"fetching {name}...", file=sys.stderr)
        title, cls, body = extract(fetch(args.branch, name))
        chapters.append({"id": name, "title": title, "class": cls, "html": body})

    data = json.dumps(chapters, ensure_ascii=False, indent=2)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// auto-generated by fetch_book.py — do not edit by hand\n")
        f.write(f"// source: https://github.com/{REPO} ({args.branch})\n")
        f.write(f"const BOOK = {data};\n")
    print(f"wrote {OUT} ({len(chapters)} sections)", file=sys.stderr)


if __name__ == "__main__":
    main()
